language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "7"
before_script:
  - npm run forever
  - npm run build
script:
  - xvfb-run node_modules/codeceptjs/bin/codecept.js run --steps